slam_toolbox:
  ros__parameters:
    odom_frame: odom
    base_frame: base_link
    map_frame: map

    scan_topic: /scan_mid360

    use_scan_matching: true
    use_scan_barycenter: false
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.17  
    transform_publish_period: 0.05 
    resolution: 0.05             
    range_threshold: 20.0          
    max_laser_range: 20.0
    min_laser_range: 0.3
    missing_data_ray_length: 2.0

    odom_frame_publish_period: 0.05
    enable_interactive_mode: false
    max_submaps_kept: 3
    loop_search_maximum_distance: 3.0
    use_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_candidate_search_interval: 3.0
    do_submap_loop_matching: true

    throttle_scans: 1
    mode: "mapping"                